name:                99Problems
version:             0.1.0.0
github:              "pdeona/99Problems"
license:             BSD3
author:              "Pedro De Ona"
maintainer:          "pedro@instantmd.co"
copyright:           "2018 Pedro De Ona"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/99Problems#readme>

dependencies:
- base >= 4.7 && < 5
- random

library:
  source-dirs: src

tests:
  99Problems-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - 99Problems
    - QuickCheck
